// glossary-data.js — reference entries for the ML/NN concepts and datasets
// this project actually uses.
//
// Every number quoted in a `formal` field was read out of the shipped
// checkpoints or the upstream source, not from the paper:
//
//   coarse.pth  335.9M params  20 layers, 20 heads, d=1280, 4 codebooks
//   c2f.pth     277.8M params  16 layers, 20 heads, d=1280, 14 codebooks (4 cond.)
//   codec.pth   150.2M params  44.1 kHz, 14 x 1024 codebooks, hop 768
//
// Entry shape: { id, term, symbol, category, formal, eli5, seeAlso }
//   formal  — technical definition, always visible
//   eli5    — plain-language version, collapsed by default
//   seeAlso — ids of related entries; validated by test/glossary.test.mjs

export const GLOSSARY_CATEGORIES = [
  { name: "All Terms",            color: "#7070a8", icon: "◈" },
  { name: "Model Architecture",   color: "#38bdf8", icon: "⬡" },
  { name: "Audio Tokens",         color: "#2dd4bf", icon: "▦" },
  { name: "Training",             color: "#fbbf24", icon: "◇" },
  { name: "Fine-tuning",          color: "#fb923c", icon: "⌥" },
  { name: "Generation",           color: "#a78bfa", icon: "↝" },
  { name: "Probing & Evaluation", color: "#4ade80", icon: "◉" },
  { name: "Training Data",        color: "#f472b6", icon: "⛁" },
];

export const GLOSSARY = [

  // ==================================================== Model Architecture

  {
    id: "transformer",
    term: "Transformer",
    symbol: "20 layers x 1280 dim",
    category: "Model Architecture",
    formal: "A neural network built from repeated blocks, each containing a self-attention layer and a feed-forward layer, with normalisation and residual connections around both. WhAM uses two separate transformer stacks: the coarse model at 20 layers and the coarse-to-fine model at 16, both 1280-dimensional with 20 attention heads. Unlike a language model, neither operates on text — the input sequence is audio tokens produced by the codec.",
    eli5: "A transformer is an assembly line with 20 identical stations. At each station, every slice of the sound gets to look at every other slice and update what it thinks it is, based on the company it keeps. By the time something reaches the end it has been revised 20 times, and each revision folded in more context about the whole clip. A 10-second coda is about 574 slices, so at every station each slice is comparing itself against 573 others at once. This is the part that could, in principle, learn that a coda is a structured object rather than a bag of clicks — and the structure-versus-timbre probe is the test of whether it did.",
    seeAlso: ["self-attention", "feed-forward", "embedding-dim", "layer-depth"],
  },
  {
    id: "self-attention",
    term: "Self-Attention",
    symbol: "Q · Kᵀ → V",
    category: "Model Architecture",
    formal: "The mechanism that lets each position in a sequence read from every other position. Each token projects a query, a key and a value; the query is compared against all keys to produce weights, and the output is the weighted sum of values. In this codebase the query, value and output projections are LoRA-wrapped while the key projection is a plain linear layer, which is the standard LoRA convention.",
    eli5: "Imagine every click in a coda asking the whole recording a question: \"who else here matters to me?\" Every other moment answers with how relevant it is, and the click rebuilds its own description mostly out of whichever moments answered loudest. Do that for every position simultaneously and you have attention. Nothing tells it what to pay attention to — the pattern of who-listens-to-whom is learned entirely from the fill-in-the-blank training. If the model has any notion of coda grammar, this is the machinery holding it.",
    seeAlso: ["attention-head", "bidirectional-attention", "relative-position-bias", "lora"],
  },
  {
    id: "attention-head",
    term: "Attention Head",
    symbol: "n_heads = 20",
    category: "Model Architecture",
    formal: "Attention is computed in parallel across several independent subspaces rather than once over the full width. WhAM uses 20 heads over 1280 dimensions, giving each head 64 dimensions to work in. Heads are concatenated and passed through a shared output projection, so different heads can specialise in different relationships without competing for the same parameters.",
    eli5: "Instead of one person reading the whole recording and forming one opinion, you send in 20 specialists at once. One might track timing, another spectral shape, another loudness. Each gets a narrow 64-number slice of the 1280 to work in, writes a short report, and the reports get stapled together. Nobody assigns the specialisms — they fall out of training, and heads often end up doing something with no clean human label. Twenty narrow readings beat one wide one, which is why almost every modern model does this.",
    seeAlso: ["self-attention", "embedding-dim"],
  },
  {
    id: "bidirectional-attention",
    term: "Bidirectional Attention",
    symbol: "not causal",
    category: "Model Architecture",
    formal: "Attention with no causal mask, so every position can attend both backwards and forwards. This is what separates a masked model from an autoregressive one: WhAM sees the entire clip including the material after a gap, which is why it can fill holes in the middle rather than only extending the end. Set by `bidirectional=True` in the transformer stack.",
    eli5: "Autocomplete on your phone only knows what you have typed so far — it can never peek ahead. WhAM is more like a crossword: you can see the letters on both sides of every blank, so filling the middle is a far easier problem than guessing blind. This is why one set of weights covers repairing a damaged recording, extending a coda, and style-transferring a drum loop — all three are just blanks in different places. It is also why a gap in the middle of a coda gets filled with something that fits *both* neighbours, which is exactly the behaviour that could disguise a lost input rhythm as a successful translation.",
    seeAlso: ["masked-token-modelling", "self-attention", "mask-token"],
  },
  {
    id: "embedding-dim",
    term: "Embedding Dimension",
    symbol: "d_model = 1280",
    category: "Model Architecture",
    formal: "The width of the vector carried at every sequence position through the transformer. WhAM uses 1280 for both the coarse and c2f stacks. This width dominates parameter count — attention and feed-forward weights scale with its square — and it is also the dimensionality of the embeddings extracted for downstream classification.",
    eli5: "Every slice of sound gets described by a list of 1280 numbers — that is the model's entire vocabulary for saying what is happening at one instant. Wider means more nuance, but cost grows with the square: doubling the width roughly quadruples the weights. It is also the number you inherit when you pull embeddings out for classification, so every downstream probe in this project works on 1280-number fingerprints, against 768 for AVES. Not a fair-fight comparison on its own — wider representations have an advantage that has nothing to do with knowing about whales.",
    seeAlso: ["transformer", "embedding", "parameter-count"],
  },
  {
    id: "layer-depth",
    term: "Layers / Depth",
    symbol: "20 coarse, 16 c2f",
    category: "Model Architecture",
    formal: "The number of stacked transformer blocks. The coarse model runs 20; the coarse-to-fine model runs 16, on the reasoning that adding spectral detail to a fixed skeleton is an easier problem than inventing the skeleton. Depth matters for probing, since intermediate layers often carry more transferable structure than the final one.",
    eli5: "Depth is how many times the sound gets rewritten on its way through. Early layers deal in local facts — \"this is a sharp transient\" — while later layers deal in whole-clip facts like \"this is a five-click rhythm with a pause after the second.\" Middle layers hold the most useful mix, which is why the embedding extractor taps layer 10 of 20 rather than the end. The detailing model gets away with 16 layers instead of 20 because adding texture to a fixed skeleton is a genuinely easier job than inventing the skeleton.",
    seeAlso: ["transformer", "hidden-activations", "coarse-to-fine"],
  },
  {
    id: "feed-forward",
    term: "Feed-Forward Network",
    symbol: "1280 → 5120 → 1280",
    category: "Model Architecture",
    formal: "The second half of each transformer block: a position-wise expansion to 4x width, a non-linearity, then projection back down. WhAM uses GEGLU, a gated variant where the expanded tensor is split in half and one half gates the other, so the down-projection sees 2560 rather than 5120. Both projections are LoRA-wrapped.",
    eli5: "Attention is where positions talk to each other; the feed-forward layer is where each position goes off and thinks alone. It briefly expands its description from 1280 numbers to 5120, applies a filter that lets one half of that decide how much of the other half survives, then compresses back to 1280. The gating is the interesting part — it lets a position suppress its own features depending on context, so the same acoustic event can mean different things in different places. Roughly two thirds of the model's weights live in these layers, not in attention.",
    seeAlso: ["transformer", "self-attention", "lora"],
  },
  {
    id: "rmsnorm",
    term: "RMSNorm",
    symbol: "x / rms(x) · g",
    category: "Model Architecture",
    formal: "Root mean square layer normalisation: divide each vector by its own root-mean-square magnitude and scale by a learned per-dimension weight. Unlike standard LayerNorm it does not subtract the mean and carries no bias term, which makes it cheaper. Applied before attention and before the feed-forward layer in every block.",
    eli5: "As numbers flow through 20 layers they drift — some balloon, some vanish, and training collapses. RMSNorm resets the volume at the entrance to each station so everything arrives at a sane scale. It is a level control, not a tone control: it divides by overall loudness and leaves the relative shape untouched. The cheap version used here skips the usual centring step, which saves real compute at 20 layers deep and costs nothing measurable in quality. Unglamorous plumbing, but without it a model this deep does not train at all.",
    seeAlso: ["transformer", "backpropagation"],
  },
  {
    id: "relative-position-bias",
    term: "Relative Position Bias",
    symbol: "32 buckets",
    category: "Model Architecture",
    formal: "How the model knows about time. Rather than adding absolute position vectors to the input, a learned bias is added to attention scores based on the distance between query and key, bucketed into 32 bins — half exact for nearby positions, half log-spaced for distant ones. Max distance is 128 positions, roughly 2.2 seconds at the codec frame rate.",
    eli5: "Attention by itself is order-blind — shuffle the clip and it genuinely cannot tell. This bolts on a sense of distance: \"you are three slices before me\" is tracked exactly, while \"you are somewhere past 60 slices away\" gets lumped into one coarse bucket. Precision is deliberately spent on the near field, which suits clicks. But note the ceiling: distances beyond 128 slices — about 2.2 seconds — are all treated as roughly the same. Any coda structure that plays out over longer than that is something the model is architecturally blurry about, which matters when you ask whether it learned grammar.",
    seeAlso: ["self-attention", "token-rate"],
  },
  {
    id: "film",
    term: "FiLM Conditioning",
    symbol: "r_cond_dim = 0",
    category: "Model Architecture",
    formal: "Feature-wise Linear Modulation — a mechanism for conditioning a network on external information by predicting per-channel scale and shift parameters. The plumbing is present throughout the VampNet stack but is inert in WhAM: `r_cond_dim` is 0 in every shipped checkpoint, and the constructor asserts it must be. Worth knowing about only so you do not mistake it for an active control surface.",
    eli5: "A dial the original architecture left on the box for steering generation from outside — \"make it more of this kind of sound.\" In WhAM the dial is wired to nothing: the code checks it is zero and refuses to run otherwise, so the conditioning layers sit in every block doing arithmetic that changes nothing. It is worth knowing this before you go looking for a way to condition generation on social unit or coda type. There is no such input. Everything you can steer, you steer through masking.",
    seeAlso: ["transformer", "vampnet-base-corpus"],
  },
  {
    id: "flash-attention",
    term: "Flash Attention",
    symbol: "flash_attn: false",
    category: "Model Architecture",
    formal: "A memory-efficient fused attention kernel that avoids materialising the full attention matrix. It is CUDA-only, and it ships disabled in every WhAM checkpoint. That single fact is why the model runs unmodified on Apple Silicon via MPS and on CPU — it was the one genuinely NVIDIA-bound component in the stack.",
    eli5: "A speed trick for attention that only works on NVIDIA graphics cards. WhAM ships with it switched off, which sounds like a downside but is precisely why the model runs on a Mac at all — it was the one component that genuinely required CUDA. Everything else was already device-agnostic. The trade is real: attention is slower and uses more memory without it. The catch worth remembering is that Apple's GPU and NVIDIA's do not produce bit-identical arithmetic, so a generation made here will not exactly match one made on the authors' machine even with the same seed.",
    seeAlso: ["self-attention", "inference"],
  },
  {
    id: "dropout",
    term: "Dropout",
    symbol: "p = 0.1",
    category: "Model Architecture",
    formal: "A regulariser that zeroes a random 10% of activations during training, forcing the network not to depend on any single pathway. Active during training only; disabled at inference via `.eval()`. The generation configs also expose a separate `dropout` field for mask-building, which is a different thing entirely and is set to 0.0 throughout.",
    eli5: "During training the model randomly loses one in ten of its own thoughts every step. That sounds cruel, but it stops it leaning too hard on any single clue and forces several independent routes to the same answer — which is what makes it robust to a noisy hydrophone recording it has never heard. At generation time nothing is dropped. Watch out for the name collision: the species presets also have a field called `dropout`, but that one is about hole-punching in the mask and is set to zero everywhere. Different thing entirely.",
    seeAlso: ["overtraining", "inference"],
  },
  {
    id: "classifier-head",
    term: "Output Classifier",
    symbol: "1280 → 4096",
    category: "Model Architecture",
    formal: "The final projection turning each 1280-dimensional position vector into logits over the token vocabulary. For the coarse model that is 4 codebooks x 1024 entries = 4096 outputs per position; for c2f it is 10 predicted codebooks x 1024 = 10240. Implemented as a weight-normalised 1x1 convolution, which is just a linear layer applied identically at every time step.",
    eli5: "The last step, where the model finally commits. It takes its rich internal description of a moment and turns it into a scorecard: for each of the 1024 possible sound-stamps, how likely is this the right one? Everything before was thinking; this is answering. The coarse model fills in four such scorecards per slice, the detailing model ten. Note that it never outputs audio — it outputs catalogue numbers, and the codec turns those back into sound. That separation is why the model can be whale-specific while the thing making the actual noise was built for music.",
    seeAlso: ["vocab-size", "codebook", "sampling-temperature"],
  },
  {
    id: "parameter-count",
    term: "Parameters",
    symbol: "764M total",
    category: "Model Architecture",
    formal: "The learned numbers in a model. Read from the shipped checkpoints: codec 150.2M, coarse 335.9M, c2f 277.8M, for roughly 764M across the stack and about 2.9 GB on disk at fp32. Be careful with counts quoted from this codebase — upstream's `num_params` helper counts only parameters with `requires_grad`, which is 40.5M of 276.4M for a default-configured model.",
    eli5: "Parameters are the model's adjustable knobs — the things training actually changes. WhAM has about 764 million across its three parts, roughly 2.9 GB on disk. When someone quotes a much smaller number for this codebase, check whether they counted every knob or only the unlocked ones: upstream's own counting helper skips anything frozen, so it reports 40.5M where the real total is 276.4M. That is a 7x discrepancy from one word in a helper function, and it is the kind of number that gets copied into a README and then into a paper.",
    seeAlso: ["frozen-weights", "embedding-dim", "checkpoint"],
  },

  // ========================================================= Audio Tokens

  {
    id: "audio-codec",
    term: "Audio Codec",
    symbol: "LAC, 150.2M",
    category: "Audio Tokens",
    formal: "The neural encoder/decoder that converts waveforms to discrete tokens and back. WhAM uses LAC, a descendant of the Descript Audio Codec, at 44.1 kHz with a hop of 768 samples. It is frozen — WhAM inherited it unchanged from VampNet and never retrained it, so the whale fine-tuning affects only how tokens are arranged, never what a token sounds like.",
    eli5: "A machine that turns sound into a list of numbered rubber stamps and can stamp them back out as audio. WhAM never touched this part — it uses the same catalogue built for music, unchanged. All the whale learning went into knowing which stamps go in which order, none into what a stamp sounds like. That has a direct consequence for the timbre question: the model literally cannot invent a sound outside the catalogue. If a translated drum loop sounds whale-like, some of that credit belongs to a music codec being asked to represent clicks, not to the whale training.",
    seeAlso: ["rvq", "codebook", "hop-length", "vampnet-base-corpus"],
  },
  {
    id: "rvq",
    term: "Residual Vector Quantisation",
    symbol: "14 stages",
    category: "Audio Tokens",
    formal: "The scheme that turns a continuous audio latent into several discrete tokens per frame. The first codebook picks the closest entry to the latent; the leftover error is quantised again by the second codebook, and so on for 14 stages. Each stage encodes what its predecessors could not, so early codebooks carry coarse structure and later ones carry fine detail.",
    eli5: "Sketch the sound roughly with one stamp. Look at what you got wrong, then pick a second stamp that cancels the biggest remaining error. Repeat 14 times, each pass smaller and fussier than the last. The payoff is that you can stop early and still have something recognisable — which is exactly what makes the two-model split possible. Stop at four and you have rhythm without realism; run all 14 and it sounds like a recording. It also means the codebooks are not interchangeable: number 12 is meaningless without 1 through 11 in front of it.",
    seeAlso: ["audio-codec", "codebook", "coarse-tokens", "fine-tokens"],
  },
  {
    id: "codebook",
    term: "Codebook",
    symbol: "14 x 1024",
    category: "Audio Tokens",
    formal: "A fixed lookup table of learned 8-dimensional vectors, one per quantisation stage. WhAM's codec carries 14 codebooks of 1024 entries each, so one frame of audio is described by 14 integers in the range 0 to 1023. The coarse model models only the first 4 of these; c2f models the remaining 10.",
    eli5: "A numbered catalogue of 1024 sound-fragments. Rather than storing a slice of audio directly, you store the catalogue number of the closest match — one small integer instead of 768 raw samples. Fourteen catalogues stacked give enough resolution to rebuild audio convincingly. There are 14 separate catalogues, not one shared one, and each was learned for its own position in the correction chain. The compression is dramatic: about 803 integers per second where the raw waveform needs 44,100 floating-point numbers.",
    seeAlso: ["rvq", "vocab-size", "latent-dim", "coarse-tokens"],
  },
  {
    id: "vocab-size",
    term: "Vocabulary Size",
    symbol: "V = 1024",
    category: "Audio Tokens",
    formal: "The number of distinct entries in each codebook, and therefore the number of classes the model predicts per position per codebook. WhAM uses 1024, plus one special MASK token appended to the embedding table. This is the direct analogue of vocabulary size in a language model, with sound-stamps in place of word-pieces.",
    eli5: "How many different stamps exist in each catalogue: 1024, plus one special blank meaning \"this bit is missing, please fill it in.\" Everything the model can ever say has to be spelled using those pieces — it is the exact equivalent of a language model's word list, with sound-fragments instead of word-pieces. The blank is a learned entry in its own right rather than a deleted slot, so the model can tell the difference between \"I do not know what was here\" and \"something quiet was here.\" That distinction is what makes infilling work.",
    seeAlso: ["codebook", "mask-token", "classifier-head"],
  },
  {
    id: "token-rate",
    term: "Frame Rate",
    symbol: "57.4 frames/s",
    category: "Audio Tokens",
    formal: "How many token positions represent one second of audio: sample rate divided by hop length, 44100 / 768 = 57.4. With 14 codebooks per frame that is about 803 integers per second, against 44100 float samples. One frame spans roughly 17.4 ms, which is the model's finest possible timing resolution.",
    eli5: "The model sees about 57 slices per second, so each slice covers roughly 17 milliseconds — the smallest interval it can distinguish. Anything faster gets blurred into one slice, which matters enormously here, because the inter-pulse interval that encodes whale body size is 2 to 10 milliseconds. That is comfortably *below* one slice. The model cannot see IPI as timing at all; if it represents it, it does so as spectral colour, since a fast click train shows up in the frequency domain as a comb. Worth holding onto before reading anything into how it handles the vowel structure.",
    seeAlso: ["hop-length", "audio-codec", "chunking"],
  },
  {
    id: "hop-length",
    term: "Hop Length",
    symbol: "768 samples",
    category: "Audio Tokens",
    formal: "The stride between consecutive codec frames, the product of the decoder's upsampling rates (6 x 4 x 4 x 2 x 2 x 2 = 768). It fixes the time resolution of everything downstream, including the granularity at which masks can be applied. At 44.1 kHz this is 17.4 ms per frame.",
    eli5: "How far the codec steps forward before taking its next snapshot: 768 audio samples, about a fiftieth of a second. Bigger hops mean fewer tokens and cheaper compute but blurrier timing, and this value was chosen for music — where a fiftieth of a second is a perfectly reasonable grain — rather than for click trains. It is also the unit everything else is quantised to. A mask cannot be finer than one hop, so \"keep every 13th frame\" really means \"keep 17 ms out of every 226 ms.\" All the temporal control you have bottoms out here.",
    seeAlso: ["token-rate", "audio-codec"],
  },
  {
    id: "latent-dim",
    term: "Latent Dimension",
    symbol: "codebook_dim = 8",
    category: "Audio Tokens",
    formal: "The width of each codebook entry, 8 in this codec. The model's input embedding reconstructs a frame by looking up all its codebook vectors, concatenating them into a 4 x 8 = 32-dimensional latent for the coarse model, then projecting up to the 1280-dimensional working width.",
    eli5: "Each stamp in the catalogue is described by only eight numbers — deliberately coarse, because a small description forces the catalogue entries to spread out and stay distinct rather than clustering. To read a moment, the model looks up its four stamps, glues the descriptions into 32 numbers, then expands that to its own 1280-number working description. So there is a narrow waist in the middle of the pipeline: everything the transformer knows about a slice arrives through 32 numbers. Whatever the codec discarded is gone before the whale-trained part ever sees it.",
    seeAlso: ["codebook", "embedding-dim", "rvq"],
  },
  {
    id: "coarse-tokens",
    term: "Coarse Tokens",
    symbol: "codebooks 1–4",
    category: "Audio Tokens",
    formal: "The first four RVQ stages, carrying the bulk of the perceptual structure: timing, rough spectral shape, envelope. The coarse model operates only on these, over 10-second chunks. This is where the whale-relevant learning lives — rhythm and coda structure are coarse-token phenomena.",
    eli5: "The rough sketch. Four stamps per slice is enough to hear where the clicks fall and roughly what they sound like, but not enough to sound real. This is the part that decides rhythm — so when you ask whether input structure survives translation, you are really asking what the coarse model did, and the detailing stage is a bystander. It is also the bigger of the two models at 335.9M parameters, and it works in 10-second chunks, which sets the longest span of coda structure it can reason about in one go.",
    seeAlso: ["rvq", "fine-tokens", "coarse-to-fine", "chunking"],
  },
  {
    id: "fine-tokens",
    term: "Fine Tokens",
    symbol: "codebooks 5–14",
    category: "Audio Tokens",
    formal: "The remaining ten RVQ stages, encoding the residual detail the coarse tokens could not capture. Predicted by the c2f model, which sees the four coarse codebooks as fixed conditioning and never alters them. This is the difference between correct rhythm that sounds synthetic and output that sounds like a recording.",
    eli5: "The shading and texture. On their own they are meaningless — they exist only as corrections layered on the rough sketch, so stamp number 12 has no interpretation without 1 through 11 underneath it. Skip them and you get the right rhythm played on a kazoo. For your purposes this is mostly the layer that makes output convincing to the ear, which is precisely why the ear is a bad judge of whether the model learned anything structural. A pseudocoda can be flawless here and nonsense in the coarse layers.",
    seeAlso: ["coarse-tokens", "coarse-to-fine", "rvq"],
  },
  {
    id: "coarse-to-fine",
    term: "Coarse-to-Fine (c2f)",
    symbol: "14 books, 4 frozen",
    category: "Audio Tokens",
    formal: "The second transformer stack: 16 layers, 1280-dimensional, configured with 14 codebooks of which the first 4 are conditioning. It sees the coarse tokens but only predicts the remaining 10, over 3-second chunks rather than 10. Coarse and c2f can be trained separately but must end up in the same model directory to be usable.",
    eli5: "A second model whose only job is detailing. It receives the rough sketch as untouchable background and paints in everything else, working in 3-second chunks rather than 10 — fine texture does not need much context, since you do not have to see a whole coda to shade one click. Two practical consequences. It can be trained separately from the coarse model, on different hardware if need be. And both halves must end up in the same model directory, because a coarse model from one training run paired with a detailer from another will produce confident, plausible-sounding garbage.",
    seeAlso: ["coarse-tokens", "fine-tokens", "chunking", "checkpoint"],
  },

  // ============================================================== Training

  {
    id: "masked-token-modelling",
    term: "Masked Token Modelling",
    symbol: "MTM",
    category: "Training",
    formal: "The training objective: hide a random subset of tokens, ask the model to predict them from what remains, score with cross-entropy. Because attention is bidirectional the model conditions on both sides of every gap, which is what makes the same trained weights usable for infilling, continuation and style transfer without task-specific heads.",
    eli5: "Training is one long game of fill-in-the-blank. Take a real coda, hide part of it at random, make the model guess what was hidden, tell it how wrong it was, repeat a few hundred thousand times. Nobody ever labels anything — the audio is its own answer key, which is why this scales to piles of unannotated recordings. The subtle part is that \"what fits this gap\" and \"what a coda is\" are not the same thing. A model can get very good at plausible local repair without ever representing coda structure, and that gap is exactly what the structure-versus-timbre probe is built to expose.",
    seeAlso: ["mask-token", "masking-schedule", "cross-entropy", "bidirectional-attention"],
  },
  {
    id: "mask-token",
    term: "MASK Token",
    symbol: "[MASK]",
    category: "Training",
    formal: "A special vocabulary entry, index 1024, standing for \"this position is hidden.\" It is added to the embedding table as a learned special token rather than reusing a real codebook entry, so the model can distinguish \"unknown\" from any particular sound. Masked positions are replaced by this token before the forward pass.",
    eli5: "A blank tile. Rather than deleting a slice of sound, you swap in a tile that means \"something was here and I am not telling you what.\" The model learns what a blank looks like and how to reason around one — which is a real skill, not a technicality. Deleting the slice outright would shorten the clip and shift everything after it, destroying the timing you were trying to preserve. The blank holds the position open so the gap keeps its exact duration. For click work that is the whole ballgame: the silence between clicks *is* the signal.",
    seeAlso: ["masked-token-modelling", "vocab-size", "masking-schedule"],
  },
  {
    id: "masking-schedule",
    term: "Masking Schedule",
    symbol: "γ(r) = cos(rπ/2)",
    category: "Training",
    formal: "The function mapping a sampled ratio to the fraction of tokens hidden. VampNet uses a cosine schedule, so training sees everything from lightly corrupted inputs to almost fully masked ones. The same function drives inference in reverse: generation starts near fully masked and unmasks progressively over a fixed number of steps.",
    eli5: "How much gets hidden varies wildly during training — sometimes almost nothing, sometimes nearly everything. The range is deliberate: it teaches small repairs and whole-cloth invention with the same weights, and generation later runs the same curve backwards, starting nearly blank and unmasking a little more each round. The cosine shape means most training draws sit toward the heavily-masked end rather than spread evenly. The model spends most of its training doing hard invention, not easy touch-ups, which is worth knowing when you wonder why it happily overwrites structure you wanted kept.",
    seeAlso: ["masked-token-modelling", "iterative-decoding", "mask-token"],
  },
  {
    id: "cross-entropy",
    term: "Cross-Entropy Loss",
    symbol: "CE",
    category: "Training",
    formal: "The training loss. For each masked position the model produces a probability distribution over the 1024 codebook entries, and the loss is the negative log probability it assigned to the correct one. Confident and right scores near zero; confident and wrong is punished heavily.",
    eli5: "The scoring system. Say \"90% sure it was stamp 412\" and be right, and you barely lose points. Say 90% and it was stamp 87, and you take a large hit. Being confidently wrong costs far more than being unsure, which pushes the model towards honest uncertainty rather than bluffing. One limitation to keep in mind: it scores stamp identity, nothing else. Guessing a stamp that sounds almost identical to the right one is penalised exactly as hard as guessing something wildly different. The loss has no notion of \"close.\"",
    seeAlso: ["label-smoothing", "backpropagation", "masked-token-modelling"],
  },
  {
    id: "label-smoothing",
    term: "Label Smoothing",
    symbol: "0.1",
    category: "Training",
    formal: "A loss modification that replaces the hard one-hot target with a softened one, here reserving 10% of the probability mass for all other classes. It discourages the model from driving any prediction to certainty, which improves calibration and reduces overfitting. Set via `CrossEntropyLoss.label_smoothing: 0.1`.",
    eli5: "Instead of telling the model \"it was stamp 412 and everything else was flat wrong,\" you say \"mostly 412, but do not rule the rest out.\" Ten percent of the credit gets spread across the other options. This stops it becoming arrogant, which matters because the loss cannot tell that neighbouring stamps sound alike — smoothing is a crude way of admitting that some of the wrong answers were nearly right. It also keeps the model from driving its own confidence to certainty, which in turn keeps generation from collapsing into the same few safe stamps.",
    seeAlso: ["cross-entropy", "overtraining"],
  },
  {
    id: "adamw",
    term: "AdamW Optimiser",
    symbol: "lr = 1e-3 / 1e-4",
    category: "Training",
    formal: "The optimiser that applies gradients. It adapts a per-parameter step size from running estimates of gradient mean and variance, with weight decay applied separately from the gradient update. WhAM uses 1e-3 for full training and 1e-4 for LoRA fine-tuning — an order of magnitude gentler, since fine-tuning should nudge rather than reshape.",
    eli5: "The thing that actually turns the knobs once training has worked out which way each should go. It keeps a running memory of how each knob has been behaving, so jittery ones get small careful turns and consistently-wrong ones get bigger confident turns. During fine-tuning every turn is ten times smaller — 0.0001 rather than 0.001 — because at that point you want to nudge a working model, not reshape it. Turning that number back up on a small dataset like DSWP is one of the faster ways to wreck a checkpoint.",
    seeAlso: ["backpropagation", "noam-scheduler", "lora"],
  },
  {
    id: "noam-scheduler",
    term: "Noam Schedule / Warmup",
    symbol: "warmup = 10 000 / 500",
    category: "Training",
    formal: "A learning-rate schedule that ramps linearly from near zero over a warmup period, then decays with the inverse square root of step count. WhAM warms up over 10 000 steps for full training and 500 for LoRA fine-tuning. Warmup exists because early gradients are large and noisy; taking full-size steps immediately destabilises transformers.",
    eli5: "Do not sprint from a standing start. For the first several thousand steps the model takes deliberately tiny steps while working out roughly which direction is downhill, then speeds up, then gradually slows again as it closes in. Skipping the warm-up tends to blow a transformer up within the first few minutes — the early gradients are enormous and mostly noise, and one full-size step in a random direction can destroy the initialisation. Fine-tuning warms up over 500 steps instead of 10,000, because the model is already in a good place and does not need to feel around for one.",
    seeAlso: ["adamw", "iteration"],
  },
  {
    id: "batch-size",
    term: "Batch Size",
    symbol: "8 full, 6 LoRA",
    category: "Training",
    formal: "How many audio excerpts are processed together before a parameter update. WhAM uses 8 for full training and 6 for fine-tuning, with 10-second excerpts for coarse and 3-second for c2f. Larger batches give less noisy gradient estimates at higher memory cost; these values are small, reflecting a 1280-wide model on a single GPU.",
    eli5: "How many clips the model studies before adjusting anything. One at a time gives jumpy, unreliable advice; eight averaged together gives a steadier signal about which direction is genuinely downhill. Eight is modest by modern standards — it is simply what fits in memory beside a 1280-wide model holding 574 positions of context. If you fine-tune on your own hardware this is the first number to drop when you run out of memory, and the trade is honest: smaller batches mean noisier updates, so you generally want a smaller learning rate alongside.",
    seeAlso: ["adamw", "iteration", "chunking"],
  },
  {
    id: "iteration",
    term: "Iteration / Step",
    symbol: "save_iters",
    category: "Training",
    formal: "One batch forward, one backward, one parameter update. This codebase counts in iterations rather than epochs because the dataset is sampled with a fixed number of examples per pass rather than enumerated. Checkpoints are written at fixed iteration counts — 10k, 50k, 100k, 300k, 500k for full training; 2k, 4k, 10k, 20k, 40k, 100k for fine-tuning.",
    eli5: "One round of study-and-adjust. Progress is counted in rounds rather than complete passes over the data, because the data is sampled at random rather than worked through in order — so \"how many epochs\" has no clean answer here. Snapshots are written at fixed round numbers, and the fine-tuning schedule saves far earlier and more often than full training: 2,000 rounds in rather than 10,000. That is not arbitrary. On a dataset the size of DSWP, the best-sounding checkpoint often arrives well before the last one, so the early saves are there to be compared, not skipped.",
    seeAlso: ["batch-size", "checkpoint", "overtraining"],
  },
  {
    id: "checkpoint",
    term: "Checkpoint",
    symbol: ".pth",
    category: "Training",
    formal: "A saved snapshot of model weights. WhAM's checkpoints carry their own hyperparameters in a `metadata.kwargs` block, so architecture is recoverable from the file without reference to any config — `coarse.pth` self-reports 20 layers, 20 heads, 4 codebooks, 1280 dimensions. Log the checkpoint used for every generation; it is a notorious source of irreproducibility here.",
    eli5: "A save file. Each holds every knob setting at the moment it was written, plus a note describing the model's shape so you can reload it without guessing — which is why `coarse.pth` can tell you it is 20 layers deep without consulting any config. Because different save files from the same run sound noticeably different, writing down which one produced a given clip is the difference between a result and an anecdote. This is the single easiest thing to lose track of in this project, and the hardest to reconstruct afterwards. Log it at generation time, not later.",
    seeAlso: ["parameter-count", "overtraining", "iteration", "seed"],
  },
  {
    id: "validation-set",
    term: "Validation Set",
    symbol: "val_freq = 1000",
    category: "Training",
    formal: "Audio held out from training and used only for measuring. Evaluated every 1000 iterations, with 2000 examples for full training and 500 for fine-tuning. Loss on training data always improves; loss on held-out data is the only honest signal of whether the model is learning structure or memorising examples.",
    eli5: "Exam questions the model never got to revise. Its score on material it has already studied keeps improving no matter what — a model with enough capacity can memorise its training set outright — so that number tells you almost nothing. The held-out score is the one that reveals whether it understood anything general. Checked every 1,000 rounds here. The catch specific to this project is that a validation split only means something if the held-out clips are genuinely independent, and with recordings from the same encounter that is harder to guarantee than it looks.",
    seeAlso: ["overtraining", "train-val-split", "iteration"],
  },
  {
    id: "overtraining",
    term: "Overtraining",
    symbol: "audit by ear",
    category: "Training",
    formal: "Continuing to fine-tune past the point where output quality peaks. Upstream explicitly warns that this degrades audio quality on small fine-tuning sets, and recommends manually auditing generations across checkpoints rather than trusting `latest`. Because the failure shows up as perceptual degradation before it shows up in loss, listening is the actual test.",
    eli5: "Studying so long you start memorising the answer sheet instead of learning the subject. On a dataset the size of DSWP this happens fast, and the model starts producing rigid, slightly broken imitations of the specific clips it saw. The nasty part is that the loss number can still look fine while the audio quietly degrades, so the usual instrument does not catch it. Upstream is unusually blunt about this: audit generations across several checkpoints by ear rather than trusting whichever one was saved last. That is not a nicety here, it is the actual procedure.",
    seeAlso: ["validation-set", "checkpoint", "species-finetuning", "dropout"],
  },
  {
    id: "frozen-weights",
    term: "Frozen Weights",
    symbol: "40.5M of 276.4M",
    category: "Training",
    formal: "Parameters excluded from gradient updates via `requires_grad = False`. In this codebase the freezing is broader than it looks: loralib's `Linear` freezes its own base weight on construction, and nothing in the training script sets it back. So the query, value, output and feed-forward projections stay frozen in every training path — only the key projection, norms, embeddings, output classifier and LoRA adapters ever update. Inherited from upstream VampNet; whether it was intended is unverified.",
    eli5: "Locking knobs so training cannot touch them. Here is the wrinkle: in this codebase most of the big knobs lock themselves the moment the model is built, and nothing ever unlocks them. The LoRA library freezes each layer's main weight as a side effect of construction, and the training script only ever *adds* restrictions. So even a full training run adjusts about 15% of the network — the key projection, the norms, the input and output layers, and the small adapters. Worth knowing before you assume domain adaptation reshaped the whole model, and worth checking against your own reading of the code, since this is inherited behaviour rather than anything documented as deliberate.",
    seeAlso: ["lora", "parameter-count", "domain-adaptation", "backpropagation"],
  },
  {
    id: "backpropagation",
    term: "Backpropagation",
    symbol: "∂L/∂w",
    category: "Training",
    formal: "The algorithm that computes how much each parameter contributed to the loss, by applying the chain rule backwards through the network. It produces gradients; the optimiser decides what to do with them. Parameters marked `requires_grad = False` are skipped, which is why the freezing behaviour above has real consequences.",
    eli5: "Working backwards from the mistake to apportion blame. If the answer was wrong, which knobs were most responsible, and which way should each move? Start at the output where blame is obvious, then push it back layer by layer to the input. That blame assignment is the gradient; a separate component decides how far to actually turn each knob. It only visits unlocked knobs — frozen ones are skipped entirely, which is why the freezing quirk in this codebase has teeth rather than being a bookkeeping detail. No blame reaches them, so they never move.",
    seeAlso: ["adamw", "cross-entropy", "frozen-weights"],
  },

  // =========================================================== Fine-tuning

  {
    id: "transfer-learning",
    term: "Transfer Learning",
    symbol: "music → whale",
    category: "Fine-tuning",
    formal: "Reusing a model trained on one domain as the starting point for another. WhAM begins from VampNet weights trained on music and adapts them to sperm whale codas in two stages. The premise is that low-level acoustic structure — transients, harmonic and inharmonic texture, temporal regularity — is shared enough that starting from music beats starting from noise.",
    eli5: "Someone who already plays piano learns guitar far faster than someone starting from nothing, because rhythm and pitch already make sense to them. WhAM starts as a music model and gets retrained on whales, keeping everything generic it knew about sound — transients, texture, timing regularity — and replacing only what is specific. This is not optional here: there is nowhere near enough sperm whale audio to train 600M parameters from scratch. But it does mean the model's instincts were formed on music, and if it hears codas as a kind of rhythm, that is where the habit came from.",
    seeAlso: ["domain-adaptation", "species-finetuning", "vampnet-base-corpus"],
  },
  {
    id: "domain-adaptation",
    term: "Domain Adaptation",
    symbol: "stage 1",
    category: "Fine-tuning",
    formal: "The first training stage, moving the model from music into general animal and marine audio. Trained on the Watkins 'Best Of' cut, BirdSet, and the AudioSet `Animal` subset combined into one directory. This stage is deliberately broad — the goal is a model fluent in biological sound, not yet in codas specifically.",
    eli5: "Step one of teaching a music model about animals. Feed it a big mixed pile — bird calls, marine mammal recordings, general animal noise off YouTube — so it stops expecting everything to have a beat and a melody. Broad exposure first, specialisation later, which is the standard move when your target dataset is tiny. All three sources go into one directory and get sampled together, so there is no curriculum and no per-source weighting. Whatever balance of birds to whales exists in that folder is the balance the model learned from.",
    seeAlso: ["transfer-learning", "species-finetuning", "watkins", "birdset", "audioset-animal"],
  },
  {
    id: "species-finetuning",
    term: "Species-Specific Fine-Tuning",
    symbol: "stage 2",
    category: "Fine-tuning",
    formal: "The second stage, narrowing the domain-adapted model onto sperm whale codas using DSWP. Run with `fine_tune: True`, which triggers `mark_only_lora_as_trainable` so only the rank-8 adapters update — about 2.9M parameters in the coarse model. The small dataset is exactly why this stage is adapter-only and why overtraining is the named risk.",
    eli5: "Step two: now that the model knows animals in general, show it sperm whales specifically. Because there is so little whale data, you let it adjust only a tiny set of knobs — about 2.9M out of 335.9M — rather than the whole model. Otherwise it would forget everything else and start parroting the handful of recordings it saw. This is the stage that makes WhAM a whale model rather than an animal model, and it is also the most fragile: small dataset, easy to overtrain, and the damage shows up in the audio before it shows up in any number you are logging.",
    seeAlso: ["domain-adaptation", "lora", "dswp", "overtraining", "catastrophic-forgetting"],
  },
  {
    id: "lora",
    term: "LoRA",
    symbol: "r = 8",
    category: "Fine-tuning",
    formal: "Low-Rank Adaptation: freeze the original weight matrix and learn a small low-rank correction B·A alongside it, where A is 8x1280 and B is 1280x8. WhAM's shipped `coarse.pth` contains 100 `lora_A` and 100 `lora_B` tensors, all non-zero, totalling 2.9M parameters. The adapters are stored unmerged, so the species-specific fine-tune is a separable component of the released checkpoint.",
    eli5: "Instead of rewriting the whole model for whales, you bolt small sticky notes onto each big frozen page: \"in this context, lean slightly this way.\" The notes are tiny — 2.9M parameters against 335.9M, well under 1% — but enough to change the model's accent without touching what it already knew. Two things make this useful to you specifically. Training only the notes means you cannot destroy the base model even if you overtrain. And the released checkpoint keeps them as separate notes rather than baking them in, so the whale-specific layer is something you can peel off and measure against, which is a free ablation nobody had to build for you.",
    seeAlso: ["lora-rank", "adapter-merge", "frozen-weights", "species-finetuning"],
  },
  {
    id: "lora-rank",
    term: "LoRA Rank",
    symbol: "LORA_R = 8",
    category: "Fine-tuning",
    formal: "The inner dimension of the low-rank correction, hard-coded to 8 at the top of `transformer.py`. It caps how much the adapter can change: a rank-8 update to a 1280x1280 matrix has 20480 parameters against 1.6M, roughly 1.3%. Applied to query, value, output and both feed-forward projections, but not to the key projection.",
    eli5: "How much room the sticky notes have to write on. Rank 8 means each note is a very short message — about 1.3% the size of the page it annotates. Enough to shift emphasis, nowhere near enough to rewrite. That constraint is the entire point: it makes overwriting prior knowledge structurally difficult rather than merely discouraged. The number is hard-coded at the top of the model file rather than exposed in any config, so changing it means editing source. And every attention layer gets notes except the key projection, which is a convention borrowed from the original LoRA paper rather than anything specific to audio.",
    seeAlso: ["lora", "catastrophic-forgetting", "self-attention"],
  },
  {
    id: "adapter-merge",
    term: "Adapter Merging",
    symbol: "W + BA",
    category: "Fine-tuning",
    formal: "Folding a LoRA correction into the base weight to produce a single dense matrix. WhAM's released checkpoints are not merged — `lora_A` and `lora_B` remain as separate tensors, which is why `_load_model` calls `load_state_dict` with `strict=False`. This is useful for ablation: the domain-adapted base and the species-specific adapters can be evaluated independently.",
    eli5: "You can either keep the sticky notes as notes, or rewrite each page with the corrections baked in and throw the notes away. Merging is slightly faster at generation time and produces one clean file; keeping them separate preserves the seam. WhAM ships unmerged. That is genuinely useful here — it means the domain-adapted animal model and the whale-specific correction are separable in the file you already downloaded, so \"how much of this behaviour is whale-specific versus general bioacoustics?\" is a question you can answer by zeroing tensors rather than by retraining anything.",
    seeAlso: ["lora", "checkpoint", "ablation"],
  },
  {
    id: "catastrophic-forgetting",
    term: "Catastrophic Forgetting",
    symbol: "—",
    category: "Fine-tuning",
    formal: "The tendency of a network to lose previously learned capability when trained on a narrow new distribution. It is the main risk in the second WhAM stage, where the fine-tuning set is small and homogeneous. Freezing the base and restricting updates to rank-8 adapters is the structural defence; auditing checkpoints by ear is the practical one.",
    eli5: "Cram for one exam and you can genuinely forget last term's material. Train a model hard on a small homogeneous pile of whale recordings and it loses its broader grip on sound — not gradually and gracefully, but sometimes quite suddenly. Keeping the base frozen and restricting updates to rank-8 notes is the structural defence, and listening across checkpoints is the practical one. This is also why acoustic translation still works at all: the model has to retain enough general audio competence to encode a drum loop or a spoken sentence sensibly before it can render it as whale.",
    seeAlso: ["lora", "overtraining", "species-finetuning", "frozen-weights"],
  },

  // ============================================================ Generation

  {
    id: "inference",
    term: "Inference",
    symbol: "eval() + no_grad",
    category: "Generation",
    formal: "Running the model to produce output rather than to learn. Dropout is disabled, gradients are not tracked, and weights do not change. Verified to run on CPU and Apple Silicon MPS in this project — the interface defaults to `device=\"cpu\"`, there are no hard `.cuda()` calls, and flash-attention ships disabled. MPS and CUDA are not bit-identical, so audit output rather than assuming parity.",
    eli5: "Using the model instead of teaching it. Nothing inside changes — dropout switches off, no blame gets computed, the weights sit still and it simply answers. On this machine it runs without an NVIDIA card, which was verified by actually executing a forward pass on both CPU and Apple's GPU rather than inferred from the code. The caveat is real though: Apple and NVIDIA arithmetic differ in the last decimal places, and 85 rounds of sampling can amplify that. So a clip generated here will not be identical to one generated on the authors' hardware even with the same seed and checkpoint. Listen before trusting.",
    seeAlso: ["flash-attention", "iterative-decoding", "checkpoint", "seed"],
  },
  {
    id: "iterative-decoding",
    term: "Iterative Decoding",
    symbol: "num_steps = 85",
    category: "Generation",
    formal: "Generation proceeds in rounds rather than one shot. Each round predicts all masked positions, keeps the most confident ones, re-masks the rest, and repeats. The species presets use 85 steps for most sources and 46 for others; `sample_cutoff` at 0.39 controls when the model stops sampling and starts taking its most likely answer.",
    eli5: "Filling in a crossword. First pass, write only the answers you are sure of. Second pass, the ones you just filled make new answers obvious. Repeat 85 times, each round easier than the last, until the grid is full. This is why the model does not need to work left-to-right: it commits in confidence order, not time order, so a click it is certain about at second nine can anchor everything around second three. Partway through it stops sampling and starts simply taking its most likely answer, which is what keeps the last rounds from injecting noise into an almost-finished clip.",
    seeAlso: ["masking-schedule", "sampling-temperature", "mask-temperature", "gumbel-sampling"],
  },
  {
    id: "sampling-temperature",
    term: "Sampling Temperature",
    symbol: "sampletemp = 1.0",
    category: "Generation",
    formal: "A divisor applied to logits before sampling. Below 1.0 sharpens the distribution towards the most likely token; above 1.0 flattens it and increases variety. The species presets leave this at 1.0, taking the model's distribution as-is and doing their shaping through masking instead.",
    eli5: "The risk dial. Turn it down and the model always plays its safest guess, which sounds clean and repetitive; turn it up and it takes chances, which sounds creative right up until it sounds broken. WhAM's presets leave it at neutral, taking the model's own distribution exactly as it comes. That is a deliberate choice worth noticing: all the shaping in this pipeline happens through *masking* — deciding what to hide and where — rather than through sampling settings. If you want more varied output, the periodic mask is a far more effective lever than this one.",
    seeAlso: ["mask-temperature", "top-p", "typical-filtering", "gumbel-sampling"],
  },
  {
    id: "mask-temperature",
    term: "Mask Temperature",
    symbol: "masktemp = 1.5",
    category: "Generation",
    formal: "A separate temperature governing which positions get kept between decoding rounds, distinct from the temperature governing which token is chosen. At 1.5 the choice of what to commit to is deliberately noisier than greedy confidence ranking, which prevents the model from locking in a rigid skeleton in the first few rounds.",
    eli5: "Two different dials that get confused constantly. One controls *what* the model writes into a blank; this one controls *which blanks it fills first*. At 1.5 the choice of what to commit to is deliberately noisier than strict confidence order — it sometimes locks in a position it was only moderately sure about. That sounds like a bug and is actually the point: strict confidence ordering makes the first few rounds lay down a rigid skeleton that every later round is then trapped by. Loosening it keeps the early structure negotiable for longer.",
    seeAlso: ["sampling-temperature", "iterative-decoding"],
  },
  {
    id: "top-p",
    term: "Top-p (Nucleus) Sampling",
    symbol: "top_p = 0",
    category: "Generation",
    formal: "Truncation that restricts sampling to the smallest set of tokens whose cumulative probability exceeds p, discarding the long tail. Disabled in every WhAM species preset (`top_p: 0`), so the full 1024-way distribution is available at every step.",
    eli5: "A rule that says \"only consider the options that together account for most of the probability, and ignore the long tail of weird outliers.\" It is the standard safety rail in text generation, where one bizarre word can derail a whole paragraph. WhAM's presets switch it off entirely and keep all 1024 options on the table however unlikely, which suits audio: a strange stamp produces a brief odd texture rather than a catastrophe, and the next decoding round can paper over it anyway. If you find generations too samey, this is one of the first knobs worth trying.",
    seeAlso: ["sampling-temperature", "typical-filtering"],
  },
  {
    id: "typical-filtering",
    term: "Typical Filtering",
    symbol: "mass = 0.15",
    category: "Generation",
    formal: "An alternative truncation that keeps tokens whose surprisal is closest to the distribution's entropy, filtering out both the too-obvious and the too-strange. The configuration is present in every preset with `typical_mass: 0.15` and `typical_min_tokens: 47`, but `typical_filtering` is `False` throughout, so those values are inert.",
    eli5: "A cleverer filter that discards both the boringly obvious answers and the bizarre ones, keeping the interestingly plausible middle — the idea being that real signals are neither maximally predictable nor random. Here is the trap: every species preset has its settings filled in with specific-looking values, and the switch that would use them is off in all of them. Those numbers do nothing. It is a good reminder to check whether a config field is actually read before spending an afternoon tuning it, which in this codebase is a live risk in more than one place.",
    seeAlso: ["top-p", "sampling-temperature"],
  },
  {
    id: "gumbel-sampling",
    term: "Gumbel Sampling",
    symbol: "argmax(logits + g)",
    category: "Generation",
    formal: "A reparameterisation trick for drawing from a categorical distribution: add independent Gumbel noise to the logits and take the argmax. Mathematically equivalent to sampling from the softmax, but expressible as a single differentiable-shaped operation with no explicit normalisation.",
    eli5: "A neat shortcut for picking randomly but fairly. Instead of converting scores into proper odds and rolling weighted dice, you add a specially-shaped dash of randomness to each raw score and take whichever ends up highest. It provably works out to the same distribution, with less arithmetic and no normalisation step. Practically, it is where all the randomness in a generation enters — fix the seed and you fix these noise draws, which is what makes a run repeatable at all. It is also the piece most sensitive to hardware differences between Apple and NVIDIA.",
    seeAlso: ["sampling-temperature", "iterative-decoding"],
  },
  {
    id: "periodic-mask",
    term: "Periodic Mask",
    symbol: "periodic_p = 13",
    category: "Generation",
    formal: "The main structural control in acoustic translation. Keeps every p-th token from the input and masks the rest, so the input survives as a sparse skeleton the model must fill around. Most species presets use 13 with width 1 — roughly one frame kept every 226 ms. This single number largely determines how much of the input's structure can survive translation.",
    eli5: "Keep every thirteenth slice of the input and delete the rest, then make the model invent what goes between. That is how a spoken sentence becomes whale-flavoured: enough scaffolding survives to shape the output, not enough to keep it sounding like speech. Put concretely, one 17 ms frame survives out of every 226 ms — so a drum hit landing between two kept frames leaves no trace at all, and its timing is reconstructed by a model that has opinions about where clicks belong. That is the crux of the whole structure-versus-timbre question. Lower the number and more input survives; raise it and you are mostly hearing the model. If you change one knob for that experiment, change this one, and report its value with every result.",
    seeAlso: ["onset-mask", "codebook-mask", "acoustic-translation", "token-rate"],
  },
  {
    id: "onset-mask",
    term: "Onset Mask",
    symbol: "onset_mask_width",
    category: "Generation",
    formal: "An additional mask region placed around detected transients, OR-ed into the main mask. Width varies by preset — 13 for Risso's dolphin and beluga, 2 for false killer whale, 4 for leopard seal. Wider values free the model to rewrite the attack of each event, which is exactly where click identity lives.",
    eli5: "Extra blanks punched around each detected hit in the input, on top of the regular every-thirteenth pattern. A wide setting lets the model reinvent the sharp start of every click; a narrow one forces it to keep the original attack. Since a click essentially *is* its attack, this quietly decides how much of the source survives. The presets vary it a lot by species — 13 for Risso's dolphin and beluga, 2 for false killer whale, 4 for leopard seal — which is worth pausing on. Those are hand-tuned per source, so a fair cross-species comparison needs you to hold this constant rather than inherit whatever the preset chose.",
    seeAlso: ["periodic-mask", "acoustic-translation"],
  },
  {
    id: "codebook-mask",
    term: "Codebook Mask",
    symbol: "n_mask_codebooks = 9",
    category: "Generation",
    formal: "Masking applied along the codebook axis rather than the time axis: everything from index 9 upward is masked, leaving codebooks 0 to 8 intact from the input. This preserves coarse and mid-level structure while forcing regeneration of the finest detail, and is applied uniformly across all species presets.",
    eli5: "The other direction you can punch holes in. Instead of hiding moments in time, you hide layers of detail: keep the first nine layers of stamps from the original and regenerate everything above. The result keeps the input's broad shape but takes on the model's fine texture. Think of it as two independent axes — the periodic mask controls *when* the model gets to invent, this controls *how deep*. Every species preset uses 9, so unlike the onset width it is at least consistent across sources. Worth changing deliberately if you want translation that is more texture-swap and less rewrite.",
    seeAlso: ["periodic-mask", "fine-tokens", "rvq"],
  },
  {
    id: "seed",
    term: "Random Seed",
    symbol: "seed = 1",
    category: "Generation",
    formal: "The initial state of the random number generator, fixing the Gumbel noise and mask sampling so a run is reproducible. Every species preset sets `seed: 1`. Note that a fixed seed reproduces a run only for a fixed checkpoint and device — MPS and CUDA will diverge from the same seed.",
    eli5: "The starting position for all the randomness, so you can run the same thing twice and get the same clip. Every species preset fixes it at 1. But reproducibility is a chain, and the seed is only one link: it also requires the same checkpoint, the same masking settings, and the same hardware. Change the graphics chip and an identical seed gives you something audibly different, because the arithmetic diverges in the last decimal places and 85 rounds of sampling amplify it. So \"seed 1\" in a lab notebook is not enough on its own — log the checkpoint and the device beside it.",
    seeAlso: ["gumbel-sampling", "checkpoint", "inference"],
  },
  {
    id: "chunking",
    term: "Chunking",
    symbol: "10 s coarse, 3 s c2f",
    category: "Generation",
    formal: "Audio longer than the model's context is processed in fixed-length pieces. The coarse model uses 10-second chunks — about 574 frames — and c2f uses 3 seconds. Structure spanning a chunk boundary is not modelled jointly, which bounds the longest temporal dependency the system can represent.",
    eli5: "The model can only hold about ten seconds in its head at once, so longer recordings get cut into pieces and handled separately. Anything connecting across a cut is invisible: a pattern spanning twenty seconds is something the architecture structurally cannot represent, no matter how much data you show it. For coda work that ceiling is usually fine, since individual codas are short. It stops being fine the moment you care about exchanges between animals — call and response, turn-taking, anything conversational lives on a timescale this model was never built to see.",
    seeAlso: ["coarse-tokens", "coarse-to-fine", "token-rate"],
  },
  {
    id: "acoustic-translation",
    term: "Acoustic Translation",
    symbol: "style transfer",
    category: "Generation",
    formal: "The first of WhAM's three surfaces: encode arbitrary audio, mask most of it, and let the whale-trained model fill the gaps, producing output in coda texture that retains some structure of the input. Requires no retraining. Whether rhythmic structure survives or output snaps to canonical coda types is precisely the question the structure-versus-timbre probe is designed to answer.",
    eli5: "Feed in a drum loop or a spoken sentence, punch most of it out, and let a model that only knows whales fill the blanks. What comes back sounds like whales, and it is genuinely striking the first time. The open question is whether it still carries the rhythm you put in, or whether the model quietly discarded it and substituted a coda it already knew. Both outcomes produce convincing audio, which is why listening cannot settle it — you have to run the output through the coda classifiers and see whether it snapped to a canonical type regardless of what you fed it. Note this needs no retraining at all: it is a property of the masking, not a separate model.",
    seeAlso: ["periodic-mask", "onset-mask", "pseudocoda", "control-condition"],
  },
  {
    id: "pseudocoda",
    term: "Pseudocoda",
    symbol: "—",
    category: "Generation",
    formal: "A novel coda-like sequence generated by the model rather than recorded from an animal. The second of WhAM's three surfaces. Their value depends entirely on whether the model learned coda grammar or only coda timbre — a distinction that cannot be settled by listening to the output, only by controlled probing.",
    eli5: "A whale call the model made up. Whether that is interesting depends entirely on whether it learned the rules of whale calls or merely what whale calls sound like — and both produce output a person would accept as plausible, which is why the ear cannot arbitrate. Compare it to a language model producing a grammatical sentence in a language you do not speak: fluent-sounding output is evidence about the model, not about the language. The useful test is distributional, not perceptual. Does a pile of pseudocodas occupy the same region as real ones, and does it have the same spread, or has it collapsed onto a few safe patterns?",
    seeAlso: ["acoustic-translation", "embedding", "null-result"],
  },

  // =================================================== Probing & Evaluation

  {
    id: "embedding",
    term: "Embedding",
    symbol: "1280-dim",
    category: "Probing & Evaluation",
    formal: "A dense vector summarising audio, taken from inside the model rather than from its output. The third of WhAM's three surfaces, used for social unit and spectral vowel classification. WhAM embeddings are 1280-dimensional; the codec-only variant is 1024-dimensional and serves as a useful control for whether the transformer adds anything the codec did not already encode.",
    eli5: "A fingerprint for a sound — 1280 numbers where similar sounds get similar lists. You never listen to it; you measure distances between fingerprints or train a small classifier on top. It is the model's opinion about a clip, frozen into numbers. This is the surface that needs no generation at all, which makes it by far the cheapest of WhAM's three capabilities to experiment with. It is also the one that answers \"did the model learn anything transferable?\" — and the codec-only version is the control you want, because if raw codec features do just as well, the whale training added nothing you were measuring.",
    seeAlso: ["hidden-activations", "probe-head", "cosine-distance", "fad"],
  },
  {
    id: "hidden-activations",
    term: "Hidden Activations",
    symbol: "layer 10 of 20",
    category: "Probing & Evaluation",
    formal: "The intermediate outputs of each transformer block, exposed via `return_activations=True`. WhAM's embedding extractor takes layer 10 of 20 from the coarse model, following the JukeMIR finding that middle layers carry the most transferable information — early layers stay close to raw acoustics, late layers specialise towards the training objective.",
    eli5: "You can tap the assembly line at any station. Tap too early and you get something barely different from the raw audio; tap too late and you get something warped towards the exact task it was trained on — predicting stamps, which is not what you care about. The middle holds the best mix, so WhAM taps station 10 of 20. That choice is inherited from music-model research rather than validated on whales, which makes it a reasonable default and a perfectly good thing to test. If layer 10 underperforms on a downstream task, trying 8 or 13 costs one flag.",
    seeAlso: ["embedding", "layer-depth", "probe-head"],
  },
  {
    id: "probe-head",
    term: "Probe / Classifier Head",
    symbol: "MLP, hidden = 128",
    category: "Probing & Evaluation",
    formal: "A small classifier trained on frozen embeddings to test what information they contain. WhAM uses a two-layer MLP with a hidden width of 128. The logic of probing: if a simple classifier can recover a property from the embeddings, that property is linearly available in the representation — the backbone encoded it, the probe merely read it out.",
    eli5: "A deliberately dim student. Freeze the big model, hand its fingerprints to a tiny classifier — two layers, 128 hidden units — and see what it can learn. If something that simple separates social units, the information was sitting right there in the fingerprint, already organised. The dimness is the whole design: a powerful classifier could dig out information the backbone had buried, which would tell you the data contains it rather than that the model represents it. Read the failures carefully though. A probe scoring badly means the information is not *easily* available, not that it is absent.",
    seeAlso: ["embedding", "hidden-activations", "control-condition"],
  },
  {
    id: "fad",
    term: "Fréchet Audio Distance",
    symbol: "FAD",
    category: "Probing & Evaluation",
    formal: "A distributional distance between two sets of audio, computed by fitting a Gaussian to each set's embeddings and measuring the Fréchet distance between them. It compares populations, not pairs — there is no notion of one clip matching another. The repo's `calculate_custom_fad.py` accepts arbitrary `.npy` embeddings, which is what makes the cross-species ladder cheap to run.",
    eli5: "A way of asking \"how similar are these two piles of sound overall?\" without ever comparing two clips directly. Describe the general shape of each pile, then measure how far apart those shapes sit. It says nothing about individual recordings, only about collections — so it cannot tell you which woodpecker clip was most coda-like, only whether woodpeckers as a group land nearer than beatboxing as a group. Two practical notes: it needs a decent number of clips per pile to estimate a shape at all, and the number is unitless, so only the *ordering* across your ladder is interpretable, never one score alone.",
    seeAlso: ["frechet-distance", "embedding", "control-condition", "ablation"],
  },
  {
    id: "frechet-distance",
    term: "Fréchet Distance (Gaussian)",
    symbol: "μ, Σ",
    category: "Probing & Evaluation",
    formal: "The underlying metric in FAD: given two multivariate Gaussians fitted to embedding sets, a closed-form distance combining the difference in means with the difference in covariances. Sensitive to both where each distribution sits and how it is spread, which is why it detects mode collapse that a mean-only comparison would miss.",
    eli5: "Compare two clouds of points by asking two questions: are their centres in the same place, and are they spread the same way? Both halves matter. A generator that produces one perfect coda over and over has the right centre and almost no spread — comparing averages alone would call that a triumph, and this catches it as the failure it is. That sensitivity to spread is exactly what makes it the right instrument for pseudocodas, where the interesting failure mode is not \"sounds wrong\" but \"sounds right and has quietly collapsed onto three variations.\"",
    seeAlso: ["fad", "embedding"],
  },
  {
    id: "ablation",
    term: "Ablation",
    symbol: "—",
    category: "Probing & Evaluation",
    formal: "Removing or altering one component to measure its contribution. The repo ships a raw/denoised/noise-profile ablation in `FAD_ablation.sh`, aimed at the open question of whether coda formant structure is a genuine acoustic property or an artifact of recording conditions. Because the released LoRA adapters are unmerged, the species-specific fine-tune is itself ablatable.",
    eli5: "Take one piece out and see what breaks. If removing the background noise makes the vowel structure disappear, then the vowel structure *was* the noise — and that is a live worry here rather than a hypothetical, raised publicly by one of the researchers whose work established the vowel finding. The repo already ships the script for the raw-versus-denoised-versus-noise-only comparison. The strongest version of that test runs across different recording equipment too, because a genuine acoustic property of whales should survive a change of hydrophone and a recording artifact generally will not.",
    seeAlso: ["control-condition", "adapter-merge", "fad", "null-result"],
  },
  {
    id: "control-condition",
    term: "Control Condition",
    symbol: "define first",
    category: "Probing & Evaluation",
    formal: "The comparison against which a result is judged, specified before the experiment runs. This project's convention is explicit about ordering, because a distance ranking is trivially easy to rationalise after the fact — any ordering of cross-species FAD scores can be made to sound like it matched acoustic intuition once you know what it is.",
    eli5: "What you are measuring against, written down before you look. Human brains are extraordinarily good at explaining why whatever happened is exactly what should have happened, and a distance ranking is unusually easy to rationalise — put woodpeckers above beatboxing and you will find a reason; put them below and you will find a different, equally satisfying one. Committing in advance is the only real defence. Concretely, before running the cross-species ladder, write down the ordering you expect and why. Then the result can actually surprise you, which is the only way it can teach you anything.",
    seeAlso: ["null-result", "ablation", "fad", "probe-head"],
  },
  {
    id: "null-result",
    term: "Null Result",
    symbol: "recorded as a result",
    category: "Probing & Evaluation",
    formal: "A finding that a hypothesised effect is absent. This project treats null results as results and records them. The click-language test is a worked example: human clicks are velaric ingressive consonants while sperm whale clicks pattern as vowel-like carriers, so no special affinity is predicted. A null confirms the phonetics; a positive would be genuinely surprising.",
    eli5: "\"Nothing happened\" is a real finding, and in this project it gets written down like any other. The click-language test is the clean example: it is expected to find nothing, because \"click\" means two entirely unrelated things across the two domains. A human click is a consonant made by sucking air against the palate; a sperm whale click is a broadband pulse that behaves like a vowel carrier. Same English word, no shared mechanism — a false cognate. Predicting the null in advance is what makes the test worth running, because it converts a boring result into a confirmation and a surprising one into something genuinely worth chasing.",
    seeAlso: ["control-condition", "ablation"],
  },
  {
    id: "cosine-distance",
    term: "Cosine Distance",
    symbol: "1 − cosθ",
    category: "Probing & Evaluation",
    formal: "A similarity measure comparing vector direction while ignoring magnitude. Used in the explorer over mean log-mel spectra as a timbre proxy. Note the failure mode already found and fixed in this codebase: over uncentred log-mel data the shared negative offset dominates the dot product and every pair returns near zero, so centring is mandatory.",
    eli5: "Compares two fingerprints by the direction they point rather than their length, so a loud and a quiet version of the same sound count as similar — usually what you want, since recording level is not part of the signal. But it has a sharp edge. If every number in your data shares a large offset, that shared component dominates and every pair comes back as nearly identical. This tool had exactly that bug: cosine over uncentred log-mel returned about zero for every comparison, which reads as \"everything matches\" rather than as an error. Centre your data first, and be suspicious of any similarity metric that never disagrees with you.",
    seeAlso: ["embedding", "dtw", "fad"],
  },
  {
    id: "dtw",
    term: "Dynamic Time Warping",
    symbol: "DTW",
    category: "Probing & Evaluation",
    formal: "An alignment algorithm matching two sequences that may run at different speeds, by stretching and compressing the time axis to minimise total distance. The explorer applies it to duration-normalised inter-click intervals, making the rhythm metric tempo-invariant by construction — tempo is reported separately so the discarded information stays visible.",
    eli5: "Compares two rhythms while ignoring how fast each was played. It stretches and squeezes one to fit the other, then measures the mismatch left over, so the same pattern at half speed still scores as the same pattern. That is deliberate here — coda types are defined by their proportional rhythm, not their absolute tempo. But it means the metric is blind by design, and blindness you forget about becomes a bug. Tempo is reported as its own separate number precisely so the discarded information stays visible on screen rather than quietly vanishing from the comparison.",
    seeAlso: ["cosine-distance", "token-rate"],
  },

  // ========================================================= Training Data

  {
    id: "watkins",
    term: "Watkins Marine Mammal Sound Database",
    symbol: "'Best Of' cut",
    category: "Training Data",
    formal: "A curated archive of marine mammal recordings collected over roughly seven decades, hosted by Woods Hole Oceanographic Institution. WhAM uses the 'Best Of' subset — the cleanest, best-labelled examples — in stage-one domain adaptation, and separately as the marine mammal test set organised by species to match the names in `prompt_configs.py`. Carries its own use conditions; check before redistributing.",
    eli5: "Roughly seven decades of underwater recordings — whales, dolphins, seals — gathered by researchers at Woods Hole and tidied into a greatest-hits selection of the cleanest, best-labelled examples. WhAM uses it twice, which is worth keeping straight: once during the first training stage to teach the model what marine mammals sound like in general, and again afterwards as the *test* material for translating other species into coda texture. Those are different roles, and the second one is where the species presets get their names. The archive has its own use conditions, so check before redistributing anything derived from it.",
    seeAlso: ["domain-adaptation", "birdset", "audioset-animal", "dswp"],
  },
  {
    id: "birdset",
    term: "BirdSet",
    symbol: "DBD-research-group/BirdSet",
    category: "Training Data",
    formal: "A large HuggingFace collection of bird vocalisation recordings with standardised splits, assembled for avian bioacoustic classification. Used in stage-one domain adaptation. Birds contribute something whales cannot: dense, highly structured, rapidly modulated vocalisations with clear temporal patterning, which broadens the model's exposure to non-human communicative sound.",
    eli5: "A big pile of bird recordings from HuggingFace, with tidy standardised splits because it was built for classification benchmarks. Birds are in the mix not because they resemble whales but because they are almost the opposite kind of animal sound — fast, tuneful, densely patterned, produced by a completely different anatomy. Seeing both stops the model assuming all animal noise works one way. If you think of the first training stage as broadening the model's idea of what counts as a vocalisation, this is the source doing most of that broadening.",
    seeAlso: ["domain-adaptation", "watkins", "audioset-animal"],
  },
  {
    id: "audioset-animal",
    term: "AudioSet (Animal label)",
    symbol: "Animal subset",
    category: "Training Data",
    formal: "Google's large-scale ontology of labelled YouTube audio segments, restricted here to the `Animal` branch, used in stage-one domain adaptation. It contributes breadth and realistic recording conditions rather than precision — labels are weak and audio quality varies widely. YouTube-derived, so it suffers link rot and carries its own terms distinct from the other sources.",
    eli5: "Animal sounds pulled from YouTube with rough labels attached — Google's giant catalogue of audio clips, filtered down to the `Animal` branch. Much messier than the other two: variable recording quality, background noise, labels that are sometimes plainly wrong. That mess is doing real work, because field recordings are messy too and a model trained only on clean archives handles them badly. The catch is reproducibility. Videos get deleted, so the exact set the authors trained on is not fully recoverable, and it carries YouTube's terms rather than a research licence.",
    seeAlso: ["domain-adaptation", "watkins", "birdset"],
  },
  {
    id: "dswp",
    term: "DSWP",
    symbol: "orrp/DSWP",
    category: "Training Data",
    formal: "The Dominica Sperm Whale Project dataset, used for stage-two species-specific fine-tuning. This is the only sperm whale coda source in the pipeline, and it is the reason that stage is LoRA-only. Important limitation: only part of it is public. Full CETI annotations are gated, and upstream states that reproducing all published results requires access that was not public at publication — plan around partial annotation coverage.",
    eli5: "The actual sperm whale codas, from a long-running research project off the island of Dominica. Smallest and most important dataset here — it is the only sperm whale audio in the whole pipeline, and everything that makes WhAM a whale model rather than an animal model came from it. It is also the one you cannot fully obtain: the public HuggingFace release is a subset, and the detailed CETI annotations are gated. Upstream says plainly that reproducing all the published results needs access that was not public at the time. So assume you are working with less than the paper had, and design experiments that do not quietly depend on annotations you do not have.",
    seeAlso: ["species-finetuning", "lora", "overtraining", "train-val-split"],
  },
  {
    id: "vampnet-base-corpus",
    term: "VampNet Base Corpus",
    symbol: "music, pre-WhAM",
    category: "Training Data",
    formal: "The music dataset behind the original VampNet checkpoints, which WhAM starts from. Not distributed with either repo — the upstream config points at local paths (`audio-train` / `audio-val`) from the authors' own machines. Practically it is the source of everything generic the model knows about sound, and the codec trained alongside it is still in use, unchanged, at 44.1 kHz.",
    eli5: "The music the model learned on before it ever heard a whale. You cannot download it — the configs point at folders on the original authors' own machines — and you do not need to, since you start from their finished weights. What matters is the inheritance. WhAM's sense of what audio fundamentally *is* was formed on songs, and the stamp catalogue it still uses today was designed to represent music at 44.1 kHz, then never retrained. Every click WhAM produces is assembled from fragments learned from music. Keep that in view when interpreting anything about coda timbre.",
    seeAlso: ["transfer-learning", "audio-codec", "domain-adaptation", "film"],
  },
  {
    id: "train-val-split",
    term: "Train/Validation Split",
    symbol: "generate_train_val_split.py",
    category: "Training Data",
    formal: "Partitioning audio so that material used for measurement is never used for learning. The repo provides `wham/finetuning/generate_train_val_split.py` for this. With a dataset as small and homogeneous as DSWP the split matters more than usual — recordings from the same encounter appearing on both sides would make validation loss meaningless.",
    eli5: "Setting some recordings aside and never training on them, so you have honest material to measure with. On a dataset this small the split is delicate rather than routine. If two clips came from the same afternoon, the same animals and the same hydrophone, putting one on each side is barely a test — the model can score well by recognising the recording conditions instead of anything about codas. A split by encounter or by individual is far more informative than a split by file, and if you are ever puzzled by suspiciously good validation numbers, this is the first place to look.",
    seeAlso: ["validation-set", "dswp", "overtraining"],
  },
];
